# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen

theme: advanced
theme_advanced_buttons1: "bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,bullist,undo,redo"
theme_advanced_buttons2: ""
theme_advanced_buttons3: ""
cleanup_on_startup: true
width: "100%"
height: "340"
